### PR TITLE
update k8s deps and controller runtime

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

Updating deps here so that other dependent projects can update.

Important thing to note is the change from `runtime.Object` to `client.Object` in a lot of places.  Thisis to accomidate changes in controller runtime API.  Actually makes things a little cleaner as `client.Object` is `meta.Object` and `runtime.Object`

```release-note
Update k8s deps to 0.20.2 and controller runtime to 0.8.3
```

### CODE REVIEW

**Comment by mhenriks** [comment]
@jakub-dzon, stepped away from this for a bit.  Yeah, of course feel free to review.  Don't expect any any changes on my end.

**Review by jakub-dzon — APPROVED** [review]

**Comment by jakub-dzon** [comment]
@mhenriks - please add a release note to the PR description.

**Pull request merged**
